<?php 

$GATC = makeGATC();
$GATC1 = makeGATC1();
$GATC2 = makeGATC2();
$GCrich = makeGCrich();
$ATrich = makeATrich();
$AlternatingAT_GC = makeAlternatingAT_GC();

$GATC1_spaces = chunk_split($GATC1, 2, ' ');
$DNA_strings[] = array('16 di-nucleotide repeats', "$GATC1", "$GATC1_spaces");

$DNA_strings[] = array('21 codon ascending scale', 'GCAAGAAACGACTGCCAAGAAGGACACATACTAAAAATGTTCCCAAGCTAAACATGGTACGTA','GCA AGA AAC GAC TGC CAA GAA GGA CAC ATA CTA AAA ATG TTC CCA AGC TAA ACA TGG TAC GTA');

$GATC_spaces = chunk_split($GATC, 3, ' ');
$DNA_strings[] = array('Repetitive codons', "$GATC", "$GATC_spaces");

$GATC2_spaces = chunk_split($GATC2, 3, ' ');
$DNA_strings[] = array('64 unique codons', "$GATC2", "$GATC2_spaces");

$DNA_strings[] = array('GC only DNA', "$GCrich", "$GCrich");

$DNA_strings[] = array('AT only DNA', "$ATrich", "$ATrich");

$DNA_strings[] = array('Alternating GC/AT DNA', "$AlternatingAT_GC", "$AlternatingAT_GC");

$DNA_strings[] = array('Human Alu repeat', 'GCCGGGCGCGGTGGCGCGTGCCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCTGGAGGATCGCTTGAGTCCAGGAGTTCTGGGCTGTAGTGCGCTATGCCGATCGGGTGTCCGCACTAAGTTCGGCATCAATATGGTGACCTCCCGGGAGCGGGGGACCACCAGGTTGCCTAAGGAGGGGTGAACCGGCCCAGGTCGGAAACGGAGCAGGTCAAAACTCCCGTGCTGATCAGTAGTGGGATCGCGCCTGTGAATAGCCACTGCACTCCAGCCTGGGCAACATAGCGAGACCCCGTCTCT', 'GCCGGGCGCGGTGGCGCGTGCCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCTGGAGGATCGCTTGAGTCCAGGAGTTCTGGGCTGTAGTGCGCTATGCCGATCGGGTGTCCGCACTAAGTTCGGCATCAATATGGTGACCTCCCGGGAGCGGGGGACCACCAGGTTGCCTAAGGAGGGGTGAACCGGCCCAGGTCGGAAACGGAGCAGGTCAAAACTCCCGTGCTGATCAGTAGTGGGATCGCGCCTGTGAATAGCCACTGCACTCCAGCCTGGGCAACATAGCGAGACCCCGTCTCT');

$DNA_strings[] = array('Human H-Ras cDNA', 'ATGACGGAATATAAGCTGGTGGTGGTGGGCGCCGGCGGTGTGGGCAAGAGTGCGCTGACCATCCAGCTGATCCAGAACCATTTTGTGGACGAATACGACCCCACTATAGAGGATTCCTACCGGAAGCAGGTGGTCATTGATGGGGAGACGTGCCTGTTGGACATCCTGGATACCGCCGGCCAGGAGGAGTACAGCGCCATGCGGGACCAGTACATGCGCACCGGGGAGGGCTTCCTGTGTGTGTTTGCCATCAACAACACCAAGTCTTTTGAGGACATCCACCAGTACAGGGAGCAGATCAAACGGGTGAAGGACTCGGATGACGTGCCCATGGTGCTGGTGGGGAACAAGTGTGACCTGGCTGCACGCACTGTGGAATCTCGGCAGGCTCAGGACCTCGCCCGAAGCTACGGCATCCCCTACATCGAGACCTCGGCCAAGACCCGGCAGGGAGTGGAGGATGCCTTCTACACGTTGGTGCGTGAGATCCGGCAGCACAAGCTGCGGAAGCTGAACCCTCCTGATGAGAGTGGCCCCGGCTGCATGAGCTGCAAGTGTGTGCTCTCCTGA', 'ATGACGGAATATAAGCTGGTGGTGGTGGGCGCCGGCGGTGTGGGCAAGAGTGCGCTGACCATCCAGCTGATCCAGAACCATTTTGTGGACGAATACGACCCCACTATAGAGGATTCCTACCGGAAGCAGGTGGTCATTGATGGGGAGACGTGCCTGTTGGACATCCTGGATACCGCCGGCCAGGAGGAGTACAGCGCCATGCGGGACCAGTACATGCGCACCGGGGAGGGCTTCCTGTGTGTGTTTGCCATCAACAACACCAAGTCTTTTGAGGACATCCACCAGTACAGGGAGCAGATCAAACGGGTGAAGGACTCGGATGACGTGCCCATGGTGCTGGTGGGGAACAAGTGTGACCTGGCTGCACGCACTGTGGAATCTCGGCAGGCTCAGGACCTCGCCCGAAGCTACGGCATCCCCTACATCGAGACCTCGGCCAAGACCCGGCAGGGAGTGGAGGATGCCTTCTACACGTTGGTGCGTGAGATCCGGCAGCACAAGCTGCGGAAGCTGAACCCTCCTGATGAGAGTGGCCCCGGCTGCATGAGCTGCAAGTGTGTGCTCTCCTGA');

$DNA_strings[] = array('Human Telomeric DNA', 'TTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGAGTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTGTTAGGGTTAGGGTTAGGG','TTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGAGTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTGTTAGGGTTAGGGTTAGGG');

$DNA_strings[] = array('Human alphoid repetitive sequence', 'CCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTATAGTCCATTCCATTCCATTCCATTCCATTCAATTCCATTCCATTACAATTCGTTCCATTCCATTCTATTCCGTACCATTCGATTCCATTCCATACCATCCATTCCATTCCATTCCATTCATTCCATTCCGTTCCATTCCGTTCATTCATTCATTCCATTCTATTCGGATTAATTCCAATCTATTCCATTCATTGCATTCTATTCCATTCCATTGCAATCGAGTTGAATACATTGCATTCTATTCATTCATTCATTCCATTCCATTCCGGAAGATTA',
'CCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTCCATTATAGTCCATTCCATTCCATTCCATTCCATTCAATTCCATTCCATTACAATTCGTTCCATTCCATTCTATTCCGTACCATTCGATTCCATTCCATACCATCCATTCCATTCCATTCCATTCATTCCATTCCGTTCCATTCCGTTCATTCATTCATTCCATTCTATTCGGATTAATTCCAATCTATTCCATTCATTGCATTCTATTCCATTCCATTGCAATCGAGTTGAATACATTGCATTCTATTCATTCATTCATTCCATTCCATTCCGGAAGATTA');

$DNA_strings[] = array('G Sequence', 
'GGGGGGGGGGGGGGGGGGGGGGGG',
'GGGGGGGGGGGGGGGGGGGGGGGG');

$DNA_strings[] = array('A Sequence', 
'AAAAAAAAAAAAAAAAAAAAAAAA',
'AAAAAAAAAAAAAAAAAAAAAAAA');

$DNA_strings[] = array('T Sequence', 
'TTTTTTTTTTTTTTTTTTTTTTTT',
'TTTTTTTTTTTTTTTTTTTTTTTT');

$DNA_strings[] = array('G Sequence', 
'CCCCCCCCCCCCCCCCCCCCCCCC',
'CCCCCCCCCCCCCCCCCCCCCCCC');

$DNA_strings[] = array('STOP in 1st Reading Frame', 
'GGGGGGGGGGGGGGGTAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
'GGGGGGGGGGGGGGGTAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG');

$DNA_strings[] = array('STOP in 2nd Reading Frames', 
'GGGGGGGGGGGGGGGGTAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
'GGGGGGGGGGGGGGGGTAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG');

$DNA_strings[] = array('STOP in 3rd Reading Frames', 
'GGGGGGGGGGGGGGGGGTAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
'GGGGGGGGGGGGGGGGGTAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG');

$DNA_strings[] = array('STOP in All Reading Frames', 
'GGGGGGGGGGGGGGGTAAATAAATAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
'GGGGGGGGGGGGGGGTAAATAAATAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG');

$DNA_strings[] = array('STOP in All, START in 1st RF', 
'GGGGGGGGGGGGGGGTAAATAAATAAGGGGGGGGGGATGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
'GGGGGGGGGGGGGGGTAAATAAATAAGGGGGGGGGGATGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG');

//use rna coding table as function for making table

?>
